groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug:slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug:slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug:slug>/',views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<username>/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

social_clone_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),

]

groups/models.py
from django.db import models
from django.urls import reverse
# hepls to remove extra characters like alphanumeric or underscore or hyphens
# the use of this is if you have string and want to use as URL then it`s going to remove spaces and add dashes ...
from django.utils.text import slugify
# install misaka in terminal
# import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# this is how we can use custom template tag
# this helps us so, we can use related_name to grab that model with get_related_name
from django import template
register = template.Library()


# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        # self.description_html = misaka.html(self.description)
        self.description_html = self.description
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
        group = models.ForeignKey(Group, related_name='memberships',on_delete=None)
        user = models.ForeignKey(User,related_name='user_groups',on_delete=None)

        def __str__(self):
            return self.user.username

        class Meta:
            unique_together = ('group','user')

groups/views.py
from django.shortcuts import render
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages

from .models import Group,GroupMember
from . import models
# Create your views here.
class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})


class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(generic.RedirectView,LoginRequiredMixin):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request,'Warning already a member!')
        else:
            messages.success(self.request,'You are now a member!')

        return super().get(request,*args,**kwargs)

class LeaveGroup(generic.RedirectView,LoginRequiredMixin):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user = self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')
        return super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<span>
<h1>{{group.name}}</h1>
<h2>Member Count: {{group.members.count}}</h2>

<div class="content">
  {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-danger">
      Leave
    </a>

  {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-success">
      Join
    </a>

  {% endif %}
</div>
</span>
{% endblock %}


{% block group_content %}

<div style="margin-left:100px;" class="col-md-8">
  {% if group.posts.count == 0 %}
    <h1>No posts in this group yet !</h1>
  {% else %}
    {% for post in group.posts.all %}
      {% include "posts/_post.html" %}
    {% endfor %}
  {% endif %}
</div>

{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}

<span>
<h4>Create a new group!</h4>

  <form action="{% url 'groups:create' %}" method="post" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large"  value="Create">
  </form>
  
</span>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}

<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
      <h2>Welcome Back!
        <a href="{% url 'posts:for_user' username=user.username %}">
          @{{user.username}}
        </a>
      </h2>
    {% endif %}
    <h2>Groups</h2>
    <p>Welcome to the groups page!</p>

  </div>
  {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
      <span class="glyphicon glyphicon-plus-sign">Create New Group!</span>
    </a>
  {% endif %}

</div>

{% endblock %}


{% block group_content %}

<div class="col-md-8">
  <div class="list-group">
    {% for group in object_list %}
    <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
      <h3 class="title list-group-item-heading">{{group.name}}</h3>
      <div class="list-group-item-text container-fluid">
          {{group.description_html|safe}}
          <div class="row">
            <div class="col-md-4">
              <span class="badge">{{group.members.count}}</span>
              Member{{group.members.count|pluralize}}
            </div>
            <div class="col-md-4">
              <span class="badge">{{group.posts.count}}</span>
              post{{group.posts.count|pluralize}}
            </div>
          </div>
        </div>
    </a>
    {% endfor %}
  </div>
</div>

{% endblock %}