accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<username>/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

social_clone_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),

]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <!-- bootstrap  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- google fonts
    font-family: 'Amatic SC', cursive;-->
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC&display=swap" rel="stylesheet">

    <!-- font awsome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'social_clone_project/css/master.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg mynav" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
        <ul class="nav navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item"> <a class="nav-link" href="{% url 'posts:create' %}">Post</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'groups:all' %}">Groups</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a> </li>
          {% else %}
            <li class="nav-item"> <a class="nav-link" href="{% url 'groups:all' %}">Groups</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a> </li>
          {% endif %}
        </ul>
      </div>
    </nav>



    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

  <h1>Welcome to Star Social!</h1>

{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}

<h1>You are now logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}

<h1>Thanks for visiting, come back soon!!</h1>

{% endblock %}